type Session @entity {
  id: ID!                        # sessionID
  logs: [Log!]! @derivedFrom(field: "session")
}

type Log @entity {
  id: ID!                        # txHash + "-" + logIndex
  session: Session!
  txHash: String
  summaries: [LogSummary!]! @derivedFrom(field: "log")
}

type LogSummary @entity {
  id: ID!                        # logId + "-" + summaryIndex
  log: Log!
  userRequest: String!
  response: String!
  toolCalls: [ToolCall!]! @derivedFrom(field: "summary")
}

type ToolCall @entity {
  id: ID!                        # logSummaryId + "-" + callIndex
  summary: LogSummary!
  name: String!
  args: String!
  result: String!
}